# Notebook Nr.03
On nous demande d'étudier l’effet de 3 éléments de symétrie différents (pas l’identité) chacun pour 1 atome différent (outre les équations, il vous est demandé d'inclure des représentations sur base de jupyter-jsmol comme vu au cours.

In [50]:
assigned_ID = "mp-7173"
chemical_formula = "ScSbPt"

beginBOLD = '\033[1m' ; endBOLD = '\033[0m'
print(beginBOLD + " Formule du matériau assigné : \n" + endBOLD) ; print(chemical_formula)
print(beginBOLD + "\n Materials Project ID : \n" + endBOLD)      ; print(assigned_ID)
print(beginBOLD + "\n------------------------------------------------------------\n" + endBOLD)

 Formule du matériau assigné : 

ScSbPt

 Materials Project ID : 

mp-7173

------------------------------------------------------------



In [51]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from pymatgen.core.operations import SymmOp
from IPython.display import Image
from jupyter_jsmol.pymatgen import quick_view

import numpy as np

In [52]:
# ----------==========     Procédure de téléchargement du fichier .CIF assigné     ==========----------

with MPRester("L41ZHCirMyRASy8QHJEO") as myCristal:
    
    structure = myCristal.get_structure_by_material_id(assigned_ID)
    
    myCifWriter = CifWriter(structure)

## 1. Premier élément de symétrie :


In [53]:
symmetry_1 = SymmOp.from_xyz_string('-x, -y, z')
matrice_1  = symmetry_1.rotation_matrix

print("Cette symmétrie est un plan miroir d'axe z. La matrice de l'opération de symétrie associée est donnée par :\n")
print(matrice_1)

Cette symmétrie est un plan miroir d'axe z. La matrice de l'opération de symétrie associée est donnée par :

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


In [54]:
view = quick_view(structure) ; display(view)
view.script('draw SYMOP 3')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Application de l'opérateur sur les coordonnées génériques (x,y,z) :

$$\begin{pmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -x \\ -y \\ z \end{pmatrix}$$

## 2. Deuxième élément de symétrie :

In [55]:
symmetry_2 = SymmOp.from_xyz_string('z, y, x')
matrice_2  = symmetry_2.rotation_matrix

print("Cette symmétrie renvoie les coordonnées x sur l'axe z et inversément.")
print("La matrice de l'opération de symétrie associée est donnée par :\n")
print(matrice_2)

Cette symmétrie renvoie les coordonnées x sur l'axe z et inversément.
La matrice de l'opération de symétrie associée est donnée par :

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [56]:
view = quick_view(structure) ; display(view)
view.script('draw SYMOP 14')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Application de l'opérateur sur les coordonnées génériques (x,y,z) :

$$\begin{pmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} z \\ y \\ x \end{pmatrix}$$

## 3. Troisième élément de symétrie :

In [57]:
symmetry_3 = SymmOp.from_xyz_string('y, z+1/2, x+1/2')
matrice_3  = symmetry_3.rotation_matrix

print("Cette symmétrie effectue une rotation autour de la droite [1 1 1].")
print("On observe également une translation de 0.5 sur les axes y et z.")
print("La matrice de l'opération de symétrie associée est donnée par :\n")
print(matrice_3)

Cette symmétrie effectue une rotation autour de la droite [1 1 1].
On observe également une translation de 0.5 sur les axes y et z.
La matrice de l'opération de symétrie associée est donnée par :

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [58]:
view = quick_view(structure) ; display(view)
view.script('draw SYMOP 89')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Application de l'opérateur sur les coordonnées génériques (x,y,z) :

$$\begin{pmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 1 & 0 & 0 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} y \\ z \\ x \end{pmatrix}$$